# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e23c2513b04f3cbd9954c269c29aac21abcfa6ec1121fd79924bbc8eccae2ff95ef00ca4d661922164cecb9dda4e353705a058e3ec226bee902df0cd1bd55dfe

test:
  secret_key_base: d8bc371e89946a90d69d3dc18833cf08d06938314868d1a2df6cd146ee2a2d26a21d810568e5a92638778ee60f6b66f99448ed16fb146901e52d80f32069ce8e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
